version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-server
    ports:
      - "55008:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    container_name: kafka-server
    restart: always
    ports:
      - "55009:9092"
      - "55010:9999"
    environment:
      HOSTNAME: 192.168.2.250
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.250:55009
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_JMX_PORT: 55010
      KAFKA_JMX_HOSTNAME: 192.168.2.250
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    container_name: kafka-manager-server
    restart: always
    ports:
      - "55011:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      # APPLICATION_SECRET: superadmin
      KM_ARGS: -Djava.net.preferIPv4Stack=true